# Source directories to format and lint
src = ["personax", "tests"]

# Exclude a variety of commonly ignored directories
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Set the maximum line length and indent width
line-length = 100
indent-width = 4

# Target Python version
target-version = "py311"

[lint]
# Enable specific rule sets
select = [
    "E",     # pycodestyle errors
    "W",     # pycodestyle warnings
    "F",     # pyflakes
    "I",     # isort (import sorting)
    "N",     # pep8-naming (naming conventions)
    "UP",    # pyupgrade (modern Python syntax)
    "B",     # flake8-bugbear (common bugs)
    "C4",    # flake8-comprehensions (list/dict comprehensions)
    "SIM",   # flake8-simplify (code simplification)
    "RET",   # flake8-return (return statements)
    "ARG",   # flake8-unused-arguments
    "PTH",   # flake8-use-pathlib (prefer pathlib over os.path)
    "PLE",   # pylint (code quality and complexity)
    "RUF",   # Ruff-specific rules
]

# Ignore specific rules
ignore = [
    "E501",    # Line too long (handled by formatter)
    "PLR0913", # Too many arguments to function call
    "PLR2004", # Magic value used in comparison
]

[lint.isort]
# Force each import to be on its own line
force-single-line = true

# Sort imports alphabetically within sections
force-sort-within-sections = true

# Define the order of import sections
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]

# Specify first-party packages for proper import grouping
known-first-party = ["prototypex"]

[lint.pydocstyle]
# Use Google-style docstring convention
convention = "google"

[lint.pylint]
# Maximum number of arguments for function
max-args = 6

# Maximum number of local variables in function
max-locals = 20

# Maximum number of branch statements in function
max-branches = 15

[format]
# Use double quotes for strings (like Black)
quote-style = "double"

# Indent with spaces rather than tabs (like Black)
indent-style = "space"

# Respect magic trailing commas for multi-line structures (like Black)
skip-magic-trailing-comma = false

# Automatically detect the appropriate line ending
line-ending = "auto"

# Enable preview mode for more aggressive formatting
preview = true

# Enable reformatting of code snippets in docstrings
docstring-code-format = true

# Format docstring code snippets with a line length of 60
docstring-code-line-length = 60